---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-records-config
  namespace: default
data:
  records.txt: |-
    test-service-2
    test-service-1
    google.com
    kube-dns A

---

apiVersion: batch/v1
kind: Job
metadata:
  name: dnsperf-deployment
  namespace: default
  labels:
    app: dnsperf
spec:
  parallelism: 5
  template:
    metadata:
      labels:
        app: dnsperf
    spec:
      containers:
      - env:
        - name: MAX_TEST_SECONDS
          value: "60"
        - name: MAX_QPS
          value: "100000"
        # please replace the ipaddr with the following command result output
        # $ kubectl get -n kube-system svc kube-dns -o go-template='{{.spec.clusterIP}}{{"\n"}}'
        - name: DNS_SERVER_ADDR
          value: "172.20.0.10"
        name: dnsperf
        image: guessi/dnsperf:alpine
        imagePullPolicy: Always
        volumeMounts:
        - name: dns-records-volume
          mountPath: /opt/
          readOnly: true
      volumes:
        - name: dns-records-volume
          configMap:
            name: dns-records-config
      restartPolicy: Never
